apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-nginx-config
  namespace: kubernetes-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
